media : "src/content/media"
content:
  - name : copywriting
    label : Copywriting
    type : collection
    path : src/content/copywriting
    filename : '{fields.title}'
    view :
      sort : [page, index]
    fields :
      - name : title
        label : Title
        type : string
      - name : page
        label : Page
        type : string
      - name : text
        label : Text
        type : string
      - name : index
        label : Index
        type : number
      - name : type
        label : Type
        type : string
  - name : posts
    label : Posts
    type : collection
    path : src/content/posts
    fields : 
      - name : published
        label : Published
        type : boolean
        default : true
      - name : date
        label : Date
        type : date
      - name : title
        label : Title
        type : string
      - name : body
        label : Content
        type : rich-text